# Generated by Django 5.1.1 on 2024-11-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidsmodel',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='menmodel',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='newarrivalmodel',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='womenmodel',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
