# Generated by Django 4.1.6 on 2023-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoeuniverse', '0002_createnewaccount_delete_createaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=400)),
            ],
        ),
    ]
