# Generated by Django 4.1.6 on 2023-04-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoeuniverse', '0003_menapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menapi',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
