# Generated by Django 4.1.6 on 2023-04-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoeuniverse', '0006_kidsapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivalApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=400)),
            ],
        ),
    ]
