# Generated by Django 4.1.6 on 2023-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imageUrl',
            field=models.URLField(default=None),
        ),
    ]
