# Generated by Django 4.1.6 on 2023-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totalAmount',
            new_name='Amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
